import NotifyGlobal from "@/components/Notify/NotifyGlobal";
import { AuthProvider } from "@/contexts/AuthContext";
import ApolloProviderWrapper from "@/graphql/apollo/apollo-provider-wrapper";
import ThemeProviderClient from "@/providers/ThemeProviderClient";
import StoreProviderWrapper from "@/store/storeProviderWrapper";
import { AnimatePresence } from "framer-motion";
import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans", // <- vira var() no CSS
  display: "swap",
});
const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={`${inter.variable} ${jetbrains.variable} antialiased`}>
        <StoreProviderWrapper>
          <ApolloProviderWrapper>
            <AuthProvider>
              <ThemeProviderClient>
                {children}
                <AnimatePresence>
                  <NotifyGlobal />
                </AnimatePresence>
              </ThemeProviderClient>
            </AuthProvider>
          </ApolloProviderWrapper>
        </StoreProviderWrapper>
      </body>
    </html>
  );
}
